# Generated by Django 2.0.3 on 2018-06-20 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_result', models.IntegerField()),
            ],
            options={
                'db_table': 'direction',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.AddField(
            model_name='direction',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Faculty'),
        ),
    ]
